[package]
name = "autobahn-hash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multiversion = "0.7"

[dev-dependencies]
criterion = "0.4"
highway = "1"

[[bench]]
name = "implementation"
harness = false
